logging:
  level:
    root: off

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parser?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
